name: Deploy Hugo Site
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Важно для тем-подмодулей!
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.134.1"  # Фиксируем версию
          extended: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libstdc++6  # Для совместимости
      - name: Build
        run: hugo --minify --gc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
